disabled_rules:
  - trailing_whitespace # "Lines should not have trailing whitespace."
  - todo # "TODOs and FIXMEs should be avoided."
  - function_parameter_count # "Number of function parameters should be low."
  - nesting # "Types should be nested at most 1 level deep, and statements should be nested at most 5 levels deep."
  - mark # "MARK comment should be in valid format."
  - conditional_binding_cascade # this kicks up warnings in Swift 2.3+

opt_in_rules:
  - force_unwrapping # "Force unwrapping should be avoided."
  - empty_count # "Prefer checking `isEmpty` over comparing `count` to zero."
  - private_outlet # "IBOutlets should be private to avoid leaking UIKit to higher layers." 
  - vertical_whitespace # "Limit vertical whitespace to a single empty line."
  - missing_docs # "Public declarations should be documented."


force_try: warning # "Force tries should be avoided."
empty_count: warning # "Prefer checking `isEmpty` over comparing `count` to zero."
line_length: # "Lines should not span too many characters."
    warning: 150
    error: 400
file_length: # "Files should not span too many lines."
    warning: 1000
    error: 2000
function_body_length: # "Functions' bodies should not span too many lines."
    warning: 100
    error: 200
type_body_length: # "Type bodies should not span too many lines."
    warning: 1000
    error: 2000
variable_name: # "Variable names should not be too long or too short"
  excluded: # whitelisted exceptions to the above rule
    - x
    - y

excluded: # what folders should be excluded from analysis? 
  - Pods

